const q=(s,c=document)=>c.querySelector(s),qa=(s,c=document)=>[...c.querySelectorAll(s)];
const reveals=qa('.reveal');
// Content must never depend on animation support. Reveal is progressive enhancement only.
if('IntersectionObserver' in window){
 const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.06,rootMargin:'0px 0px 80px 0px'});
 reveals.forEach(el=>observer.observe(el));
 setTimeout(()=>reveals.forEach(el=>el.classList.add('visible')),1400);
}else{reveals.forEach(el=>el.classList.add('visible'))}
const glow=q('.cursor-glow');window.addEventListener('pointermove',e=>{if(glow){glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'}});
qa('.tilt').forEach(card=>{card.addEventListener('pointermove',e=>{if(innerWidth<900)return;const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(900px) rotateX(${-y*4}deg) rotateY(${x*5}deg) translateY(-2px)`});card.addEventListener('pointerleave',()=>card.style.transform='')});
const menu=q('.menu'),links=q('.nav-links');menu?.addEventListener('click',()=>links.classList.toggle('open'));qa('.nav-links a').forEach(a=>a.addEventListener('click',()=>links.classList.remove('open')));
const stage=q('.hero-stage');window.addEventListener('pointermove',e=>{if(!stage||innerWidth<900)return;const x=(e.clientX/innerWidth-.5)*8,y=(e.clientY/innerHeight-.5)*-8;stage.style.transform=`rotateY(${x}deg) rotateX(${y}deg)`});

// Navigation state and subtle scroll progress
const nav=q('.nav');const setNav=()=>nav?.classList.toggle('scrolled',scrollY>40);addEventListener('scroll',setNav,{passive:true});setNav();
qa('a[href^="#"]').forEach(a=>a.addEventListener('click',()=>{const id=a.getAttribute('href');if(id&&id.length>1)q(id)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}));

// Cinematic ambient motion: slow, pointer-responsive and intentionally restrained.
const world=q('.world-bg'),sculpture=q('.sculpture');let tx=0,ty=0,cx=0,cy=0;
addEventListener('pointermove',e=>{tx=(e.clientX/innerWidth-.5);ty=(e.clientY/innerHeight-.5)});
(function ambient(){cx+=(tx-cx)*.035;cy+=(ty-cy)*.035;if(sculpture&&innerWidth>900)sculpture.style.transform=`rotateY(${cx*8}deg) rotateX(${-cy*6}deg) translate3d(${cx*8}px,${cy*8}px,0)`;if(world)world.style.transform=`translate3d(${cx*-10}px,${cy*-8}px,0) scale(1.03)`;requestAnimationFrame(ambient)})();
// Reveal elements receive a subtle stagger without slowing navigation.
qa('.project,.cert,.achievement-grid article').forEach((el,i)=>el.style.transitionDelay=((i%4)*70)+'ms');

const progress=q('.scroll-progress');
const paintProgress=()=>{if(!progress)return;const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(max>0?scrollY/max*100:0)+'%'};
addEventListener('scroll',paintProgress,{passive:true});paintProgress();
qa('.hero h1 .hero-line,.hero h1 em').forEach((el,i)=>{el.animate([{opacity:0,transform:'translateY(34px)',filter:'blur(8px)'},{opacity:1,transform:'translateY(0)',filter:'blur(0)'}],{duration:900,delay:180+i*110,easing:'cubic-bezier(.2,.8,.2,1)',fill:'both'})});

const scrollProgress=q('.scroll-progress');
const updateScrollProgress=()=>{if(!scrollProgress)return;const d=document.documentElement.scrollHeight-innerHeight;scrollProgress.style.width=(d>0?scrollY/d*100:0)+'%'};
addEventListener('scroll',updateScrollProgress,{passive:true});updateScrollProgress();

// WebGL2 phosphor shader, adapted from the supplied component for this static portfolio.
(()=>{const canvas=q('#shader-bg');if(!canvas||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const gl=canvas.getContext('webgl2',{premultipliedAlpha:false});if(!gl){canvas.style.display='none';return}
const vert='#version 300 es\nprecision highp float;layout(location=0) in vec2 a_pos;out vec2 v_uv;void main(){v_uv=a_pos*.5+.5;gl_Position=vec4(a_pos,0.,1.);}';
const frag='#version 300 es\nprecision highp float;out vec4 fragColor;in vec2 v_uv;uniform vec3 iResolution;uniform float iTime;uniform int iFrame;uniform vec4 iMouse;void mainImage(out vec4 o,in vec2 fc){vec2 r=iResolution.xy;float t=iTime;vec3 FC=vec3(fc,t);o=vec4(0.);float s=0.;for(float i=0.,z=0.,d=0.;i++<80.;o+=(cos(s+vec4(0.,1.,8.,0.))+1.)/d){vec3 p=z*normalize(FC.rgb*2.-r.xyy);vec3 a=normalize(cos(vec3(5.,0.,1.)+t-d*4.));p.z+=5.;a=a*dot(a,p)-cross(a,p);for(d=1.;d++<9.;)a-=sin(a*d+t).zxy/d;z+=d=.1*abs(length(p)-3.)+.07*abs(cos(s=a.y));}o=tanh(o/5e3);o.rgb*=vec3(.66,.9,.62);o.rgb=mix(o.rgb,o.bgr,.12);o.rgb*=.7;}void main(){mainImage(fragColor,gl_FragCoord.xy);fragColor.a=1.;}';
const compile=(type,src)=>{const sh=gl.createShader(type);gl.shaderSource(sh,src);gl.compileShader(sh);return gl.getShaderParameter(sh,gl.COMPILE_STATUS)?sh:null};const vs=compile(gl.VERTEX_SHADER,vert),fs=compile(gl.FRAGMENT_SHADER,frag);if(!vs||!fs){canvas.style.display='none';return}const prog=gl.createProgram();gl.attachShader(prog,vs);gl.attachShader(prog,fs);gl.linkProgram(prog);if(!gl.getProgramParameter(prog,gl.LINK_STATUS)){canvas.style.display='none';return}gl.deleteShader(vs);gl.deleteShader(fs);const vao=gl.createVertexArray(),vbo=gl.createBuffer();gl.bindVertexArray(vao);gl.bindBuffer(gl.ARRAY_BUFFER,vbo);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,2,gl.FLOAT,false,0,0);const ur=gl.getUniformLocation(prog,'iResolution'),ut=gl.getUniformLocation(prog,'iTime'),uf=gl.getUniformLocation(prog,'iFrame'),um=gl.getUniformLocation(prog,'iMouse');let mx=0,my=0,frame=0,start=performance.now(),raf=0,visible=true;const size=()=>{const d=Math.min(devicePixelRatio||1,innerWidth<700?1:1.35),w=Math.floor(innerWidth*d),h=Math.floor(innerHeight*d);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h)}};addEventListener('resize',size,{passive:true});addEventListener('pointermove',e=>{mx=e.clientX;my=innerHeight-e.clientY},{passive:true});document.addEventListener('visibilitychange',()=>visible=!document.hidden);size();const draw=now=>{raf=requestAnimationFrame(draw);if(!visible)return;frame++;gl.useProgram(prog);gl.uniform3f(ur,canvas.width,canvas.height,Math.min(devicePixelRatio||1,1.35));gl.uniform1f(ut,(now-start)/1000*.32);gl.uniform1i(uf,frame);gl.uniform4f(um,mx,my,0,0);gl.bindVertexArray(vao);gl.drawArrays(gl.TRIANGLES,0,3)};raf=requestAnimationFrame(draw)})();

// Supplied Works Wheel behavior, adapted to the portfolio's existing no-framework stack.
(()=>{const stage=q('.wheel-stage'),wrap=q('.wheel-cards');if(!stage||!wrap)return;const cards=qa('.wheel-card',wrap),label=q('.wheel-label'),title=q('.wheel-title'),index=q('.wheel-index');const n=cards.length,last=n-1;cards.forEach((c,i)=>{const li=document.createElement('li'),b=document.createElement('button');b.type='button';b.textContent=String(i+1).padStart(2,'0')+' '+c.dataset.title;b.addEventListener('click',()=>to(i+1));li.append(b);index.append(li)});const buttons=qa('button',index);let turn=0,target=0,drag=null,settle=0,active=-1;const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));const to=v=>target=clamp(v,0,last+1);const metrics=()=>{const w=stage.clientWidth,h=stage.clientHeight,cw=Math.min(h*.38*1.45,w*(innerWidth<700?.68:.34)),ch=cw/1.45;return{cw,ch,drum:ch*2.22,ring:ch*1.14,bow:ch*1.82,depth:ch*2.7,scale:clamp((((2*Math.PI*(ch*1.14))/n)*.82)/(cw||1),.16,1)}};let m=metrics();const resize=()=>m=metrics();addEventListener('resize',resize,{passive:true});const draw=()=>{turn+= (target-turn)*(matchMedia('(prefers-reduced-motion: reduce)').matches?1:.12);const mix=clamp(turn,0,1),pos=Math.max(0,turn-1);stage.style.perspective=m.depth+'px';wrap.style.transform='translateZ('+(-mix*m.drum)+'px)';cards.forEach((card,i)=>{const d=i-pos,ringDeg=d*(360/n),drumDeg=d*40,bow=-m.bow*(1-Math.cos(drumDeg*Math.PI/180));card.style.transform='translateX('+(mix*bow)+'px) rotateZ('+((1-mix)*ringDeg)+'deg) translateY('+(-(1-mix)*m.ring)+'px) rotateX('+(mix*drumDeg)+'deg) translateZ('+(mix*m.drum)+'px)';card.style.opacity=mix>.5&&Math.abs(d)>1.6?'0':'1';card.style.zIndex=String(Math.round(100-Math.abs(d)*2));card.firstElementChild.style.transform='scale('+(m.scale+(1-m.scale)*mix)+')'});label.style.opacity=String(1-mix);title.style.opacity=String(mix);const near=clamp(Math.round(pos),0,last);if(near!==active){active=near;title.textContent=cards[active].dataset.title;buttons.forEach((b,i)=>b.classList.toggle('active',i===active))}requestAnimationFrame(draw)};requestAnimationFrame(draw);stage.addEventListener('wheel',e=>{const next=target+e.deltaY/900;if(next>0&&next<last+1)e.preventDefault();to(next);clearTimeout(settle);settle=setTimeout(()=>to(Math.round(target)),140)},{passive:false});stage.addEventListener('pointerdown',e=>{drag=e.clientY;stage.setPointerCapture(e.pointerId)});stage.addEventListener('pointermove',e=>{if(drag===null)return;to(target+(drag-e.clientY)/420);drag=e.clientY});stage.addEventListener('pointerup',()=>{drag=null;if(target>1)to(Math.round(target))});stage.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){to(Math.round(target)+1);e.preventDefault()}else if(e.key==='ArrowUp'){to(Math.round(target)-1);e.preventDefault()}})})();
